# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61mera.proto\x12\x06\x63\x61mera\"\x14\n\x12ListCamerasRequest\":\n\x13ListCamerasResponse\x12#\n\x07\x63\x61meras\x18\x01 \x03(\x0b\x32\x12.camera.CameraInfo\"\x1f\n\x11\x43\x61meraInfoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"b\n\nCameraInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x0b\n\x03\x66ps\x18\x05 \x01(\x05\x12\x0e\n\x06status\x18\x06 \x01(\t\"M\n\x0c\x46rameRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0b\n\x03\x66ps\x18\x04 \x01(\x05\"_\n\rStreamRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0b\n\x03\x66ps\x18\x04 \x01(\x05\x12\x0f\n\x07quality\x18\x05 \x01(\x05\"\x81\x01\n\rFrameResponse\x12\x11\n\tcamera_id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12\r\n\x05\x65rror\x18\x07 \x01(\t2\x98\x02\n\rCameraService\x12H\n\x0bListCameras\x12\x1a.camera.ListCamerasRequest\x1a\x1b.camera.ListCamerasResponse\"\x00\x12@\n\rGetCameraInfo\x12\x19.camera.CameraInfoRequest\x1a\x12.camera.CameraInfo\"\x00\x12\x39\n\x08GetFrame\x12\x14.camera.FrameRequest\x1a\x15.camera.FrameResponse\"\x00\x12@\n\x0cStreamFrames\x12\x15.camera.StreamRequest\x1a\x15.camera.FrameResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTCAMERASREQUEST']._serialized_start=24
  _globals['_LISTCAMERASREQUEST']._serialized_end=44
  _globals['_LISTCAMERASRESPONSE']._serialized_start=46
  _globals['_LISTCAMERASRESPONSE']._serialized_end=104
  _globals['_CAMERAINFOREQUEST']._serialized_start=106
  _globals['_CAMERAINFOREQUEST']._serialized_end=137
  _globals['_CAMERAINFO']._serialized_start=139
  _globals['_CAMERAINFO']._serialized_end=237
  _globals['_FRAMEREQUEST']._serialized_start=239
  _globals['_FRAMEREQUEST']._serialized_end=316
  _globals['_STREAMREQUEST']._serialized_start=318
  _globals['_STREAMREQUEST']._serialized_end=413
  _globals['_FRAMERESPONSE']._serialized_start=416
  _globals['_FRAMERESPONSE']._serialized_end=545
  _globals['_CAMERASERVICE']._serialized_start=548
  _globals['_CAMERASERVICE']._serialized_end=828
# @@protoc_insertion_point(module_scope)
